//! Regenerates the HAP packet fixtures that `hap_conformance.rs` asserts
//! against. Run manually, commit the result:
//!
//! ```sh
//! cargo test --test gen_fixtures -- --ignored --nocapture
//! ```
//!
//! This is the only place a fixture touches ffmpeg. `hap_conformance.rs` reads
//! the committed bytes and is pure Rust, so it keeps running unchanged when the
//! demuxer is replaced (web-port.md §4) and under `wasm32-unknown-unknown`.

// Drives the ffmpeg transcode/demux path; nothing here is portable.
#![cfg(feature = "ffmpeg")]

use std::path::{Path, PathBuf};

use ffmpeg_next as ff;
use vidiotic_bake::hap;

/// FNV-1a. Not cryptographic — this only needs to notice a changed byte.
/// Duplicated in `hap_conformance.rs`; that test must not depend on this one.
fn hash(b: &[u8]) -> u64 {
    b.iter().fold(0xcbf2_9ce4_8422_2325, |h, &x| {
        (h ^ u64::from(x)).wrapping_mul(0x0000_0100_0000_01b3)
    })
}

/// Clips live outside this crate; the workspace root holds them.
fn clips_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap().join("clips")
}

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

/// Packets to lift per clip, spread across the file rather than clustered at
/// the head so a fixture set exercises more than the first GOP-equivalent.
const PICK: [usize; 3] = [0, 17, 41];

#[test]
#[ignore = "fixture generator; run manually and commit the output"]
fn gen_fixtures() {
    ff::init().expect("ffmpeg init");
    let out = fixtures_dir();
    std::fs::create_dir_all(&out).expect("create fixtures dir");

    let mut written = 0;
    // name \t texture_count \t format \t video_mode \t main_len \t main_hash \t alpha_len \t alpha_hash
    let mut goldens = String::from(
        "# Generated by `cargo test --test gen_fixtures -- --ignored`. Do not hand-edit.\n\
         # name\ttex\tformat\tvmode\tmain_len\tmain_hash\talpha_len\talpha_hash\n",
    );
    let mut names: Vec<String> = Vec::new();
    for entry in std::fs::read_dir(clips_dir()).expect("read clips dir") {
        let path = entry.expect("dir entry").path();
        if path.extension().is_none_or(|e| e != "mov") {
            continue;
        }
        let stem = path.file_stem().unwrap().to_string_lossy().to_string();

        let mut ictx = ff::format::input(&path).expect("open clip");
        let stream = ictx
            .streams()
            .best(ff::media::Type::Video)
            .expect("video stream");
        let idx = stream.index();
        let params = stream.parameters();
        assert_eq!(params.id(), ff::codec::Id::HAP, "{stem} is not HAP");

        // The FourCC decides texture_count (2 only for HapM); record it beside
        // the packet so the conformance test does not have to guess.
        let tag = unsafe { (*params.as_ptr()).codec_tag }.to_le_bytes();
        let fourcc = String::from_utf8_lossy(&tag).to_string();

        let mut n = 0usize;
        for (stream, packet) in ictx.packets() {
            if stream.index() != idx {
                continue;
            }
            let this = n;
            n += 1;
            if !PICK.contains(&this) {
                continue;
            }
            let data = packet.data().expect("packet data");
            let n = this;
            let name = format!("{stem}_{fourcc}_{n:03}.hap");
            std::fs::write(out.join(&name), data).expect("write fixture");

            // Record what the current decoder makes of it. These goldens lock
            // *present* behaviour so a demuxer swap or a wasm build can be
            // proven byte-identical; they are not an independent oracle.
            let tex = u8::from(fourcc == "HapM") + 1;
            let (mut main, mut alpha) = (Vec::new(), Vec::new());
            let meta = hap::decode_frame(data, tex, &mut main, &mut alpha).expect("decode fixture");
            goldens.push_str(&format!(
                "{name}\t{tex}\t{:?}\t{}\t{}\t{:016x}\t{}\t{:016x}\n",
                meta.format,
                meta.video_mode,
                main.len(),
                hash(&main),
                alpha.len(),
                hash(&alpha),
            ));

            println!("wrote {name} ({} bytes packet, {} bytes BC)", data.len(), main.len());
            names.push(name);
            written += 1;
        }
    }
    assert!(written > 0, "no fixtures written — is clips/ populated?");

    // Prune goldens for fixtures that no longer exist, by rewriting wholesale.
    std::fs::write(out.join("goldens.tsv"), &goldens).expect("write goldens");

    // Any stale .hap not regenerated this run would silently keep passing.
    for entry in std::fs::read_dir(&out).expect("read fixtures dir") {
        let p = entry.expect("dir entry").path();
        if p.extension().is_some_and(|e| e == "hap") {
            let n = p.file_name().unwrap().to_string_lossy().to_string();
            assert!(names.contains(&n), "stale fixture {n} — delete it and rerun");
        }
    }
    println!("{written} fixtures + goldens.tsv in {}", out.display());
}
